apiVersion: v1
kind: Pod
metadata:
  labels:
    run: autoinstrumentationrepro
  name: autoinstrumentationrepro
  annotations:
    instrumentation.opentelemetry.io/inject-dotnet: opentelemetry/auto-instrumentation

spec:
  containers:
    - image: repro:latest
      name: autoinstrumentationrepro
      resources: {}
      imagePullPolicy: Never
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
